### ISSUE TITLE
Unable to delete individual blocks on development branch

### ISSUE THREAD

**Issue by anomaly256** [EinsteinsWorkshop/BlocksCAD#10]
After checking out 58a2fdb7856580b03b1aed6fada17ed26746da07 the dropdown menu for blocks only contains 'disable all blocks' and 'enable all blocks' and no longer shows the option to disable individual blocks nor delete them.

**Comment by anomaly256** [comment]
Note: this only seems to happen if I rebuild anything, using the *_compressed.js files from the git repo seem to work ok

**Comment by yoderjen** [comment]
Let me see if I can reproduce this problem.  I haven't seen it before.  Thanks!

**Comment by yoderjen** [comment]
Okay, this is related to issue #9 - see my comment there.  Short form - don't change blockly/msg/json/en.json, undo your changes to blockly/msg/js/en.js, and this should fix the BlocksCAD problems.  I'll see if I can figure out why the Blockly message generation code isn't working.

**Comment by yoderjen** [comment]
I fixed en.json in the latest commit to development (795047f).  This should solve your problems.  Thanks for pointing this out!
