### ISSUE TITLE
using variable in sides block gives NaN in generated code

### ISSUE THREAD

**Issue by yoderjen** [EinsteinsWorkshop/BlocksCAD#13]
declaring a variable and then using that variable in the sides block produces illegal code like:

item = 10;

assign($fn=NaN){
}

**Comment by mattminuti** [comment]
This was introduced in 4f7b384, unfortunately. Couldn't have been in a more inconvenient commit.

**Comment by yoderjen** [comment]
I see the problem.  I'll do a fix.

**Comment by yoderjen** [comment]
Fixed in the latest code in the development branch.  thanks!
