### ISSUE TITLE
Calculating with angles

### ISSUE THREAD

**Issue by thesourcerer8** [EinsteinsWorkshop/BlocksCAD#18]
When I take a Rotation block, it has an Angle sub-block. If then then want to multiply that angle by a certain factor, I take a multiply block, insert it into the Rotation block, instead of the Angle block, and then take the Angle block that fell out into the Multiply block. Then I add a number block as the factor, or some variable block as the second multiplier. But this does not work, a multiplication only wants to operate on numbers, not on angles. 5*10°=50° does not seem to work. The workaround I have found so far is to use a number block instead of the Angle block, and write the degrees as a number in there. Then the multiplication works. The disadvantage is that I cannot graphically select the angle anymore.

**Comment by yoderjen** [comment]
I have not been able reproduce this error.  In the code produced from the blocks (viewable from the "code" tab on the upper right), the angle block simply produces a number, and 5 \* 10deg = 50.

![err](https://cloud.githubusercontent.com/assets/10271662/10558937/61fbf568-74b1-11e5-949e-26231a5d5879.jpg)

rotate([(5 \* 10), 0, 0]){
  cylinder(r1=5, r2=5, h=20, center=false);
}

Can you provide more details on what you are seeing?

**Comment by thesourcerer8** [comment]
Great, it works. Yes. It seems to me this was solved already. Sorry, I should have tested it again, before reporting it.
