### ISSUE TITLE
XML has incorrect namespace

### ISSUE THREAD

**Issue by KitWallace** [EinsteinsWorkshop/BlocksCAD#21]
Exported XML files have the namespace declared as 

xmlns="http://www.w3.org/1999/xhtml"

but this is not XHTML and the document is thus not rendered by a browser  as XML

Suggest removing the xmlns attribute altogether or giving it a URI appropriate to BlockSCAD eg 
http://blockscad.einsteinsworkshop.com

**Comment by KitWallace** [comment]
issue  has not been fixed - as of 22 Jan 

&lt;xml xmlns="http://www.w3.org/1999/xhtml">

**Comment by yoderjen** [comment]
I'll give it a blockscad url.  WIP.

**Comment by yoderjen** [comment]
This is fixed in the development branch.  It should go out in the new release this week.  Thanks for reminding me to fix this issue.
