### ISSUE TITLE
Strings not handled corrected as parameters

### ISSUE THREAD

**Issue by KitWallace** [EinsteinsWorkshop/BlocksCAD#26]
![image](https://cloud.githubusercontent.com/assets/191645/13062454/bb131610-d436-11e5-9a6f-f91fa59f4812.png)

creates this openSCAD 

module makeText(label) {
  linear_extrude( height=10, twist=0, center=false){
    text("label", font = "Liberation Serif", size = 10);
  }

}

makeText(hello);

but it should be 

module makeText(label) {
  linear_extrude( height=10, twist=0, center=false){
    text(label, font = "Liberation Serif", size = 10);
  }

}

makeText("hello");

**Comment by yoderjen** [comment]
Fixed and released.  Thanks for the report!
