### ISSUE TITLE
Ubuntu Studio 15.10 localhost fails

### ISSUE THREAD

**Issue by CoolGames** [EinsteinsWorkshop/BlocksCAD#28]
# Ubuntu Studio 15.10 using Chrome Version 48.0.2564.116 (64-bit) on Apache2 with
### Ubuntu Studio 15.10 localhost fails with ABORT not RENDER as online does

_Installed nodejs as required_

```
apt-get install nodejs
```
### Then clone and try

```
cd '/var/www/html'
git clone https://github.com/EinsteinsWorkshop/BlocksCAD.git
```
## or maybe this relates to displayed results

```
python -m SimpleHTTPServer 9000
Serving HTTP on 0.0.0.0 port 9000 ...

127.0.0.1 - - [14/Apr/2016 16:13:27] "GET /blockscad/lightgl.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2016 16:13:27] code 404, message File not found

```
### SimpleHTTPServer 'http://localhost:9000/'

![blockscad - screenshot_2016-04-14_16-28-32](https://cloud.githubusercontent.com/assets/149711/14542770/a5805136-025e-11e6-86e8-0c0daaaa2cc0.png)

**Comment by yoderjen** [comment]
Are you cloning the master branch?

**Comment by yoderjen** [comment]
Here's what you need to do:  

from your root directory, enter the "blockscad" directory, then find the file "blockscad.js".  Edit line 34:

Blockscad.offline = true;

(it is currently set at false and if you switch it you'll see the same behaviour as our production website except for no cloud backend)

**Comment by CoolGames** [comment]
### Thanks that is easy.

I  copied path to clipboard where there is README.md on github then 

```
cd /var/www/html 
git clone https://github.com/EinsteinsWorkshop/BlocksCAD.git
```

.

## Then edit line 34 in /blockscad/blockscad.js set to true.

![local - screenshot_2016-04-14_22-02-01](https://cloud.githubusercontent.com/assets/149711/14549312/a65a775c-028c-11e6-8b9e-76246410ad26.png)

**Comment by yoderjen** [comment]
Glad that worked for you.  I'm closing this issue.
