### ISSUE TITLE
BlocksCAD to OpenScad shifted text

### ISSUE THREAD

**Issue by CoolGames** [EinsteinsWorkshop/BlocksCAD#30]
## Screen shots of 3D text on modified cube reveals a shift when save as SCAD is used.

STL(binary) appears correct in Mesh Lab.
### Notice second line is also shifted from G over N

![cool games nametag - meshlab - screenshot_2016-04-28_15-01-16](https://cloud.githubusercontent.com/assets/149711/14898031/bfd3cf8c-0d52-11e6-9e1e-3c5921faa58b.png)
![cool games nametag - openscad - screenshot_2016-04-28_15-04-25](https://cloud.githubusercontent.com/assets/149711/14898033/bfd80656-0d52-11e6-838b-14ed2560a48f.png)
![cool games nametag - screenshot_2016-04-28_14-44-32](https://cloud.githubusercontent.com/assets/149711/14898032/bfd42d2e-0d52-11e6-840a-172b171462bd.png)

**Comment by yoderjen** [comment]
Interesting.  I can see one Blockscad bug, which is that we should be reporting the font used as "Roboto:style=Bold" for openscad, but that doesn't fix the size issue.  I don't know whose font is the "right" size.  A size 20 font is clearly rendering much larger in openscad.  I'll look into this.

**Comment by yoderjen** [comment]
Openscad font sizes are in points (that's what their font library uses), Blockscad's font sizes are in pixels (thats what our font library uses).  Bleah.

**Comment by yoderjen** [comment]
I fixed the font size but forgot to fix the roboto style to be bold.  Oops.  Well, at least the size is fixed in the current production version.
