### ISSUE TITLE
Generate Button

### ISSUE THREAD

**Issue by mskmoorthy** [EinsteinsWorkshop/BlocksCAD#35]
Generate Button and the view frame are not showing up in Chrome Version 51.0.2704.106 (64-bit) running ubuntu 14.04

**Comment by yoderjen** [comment]
Does it work in firefox for you?  What happens if you refresh the Chrome page?

**Comment by mskmoorthy** [comment]
Viewport does not show (along with generate button) in Firefox 49.0 - Refresh in Chrome does not help either

**Comment by yoderjen** [comment]
Is this report for the website at blockscad.einsteinsworkshop.com,  or are you using the source to get your own copy of the page running?

**Comment by mskmoorthy** [comment]
I am using the source code to get my own copy running. (Sorry for not explicitly writing it)

**Comment by yoderjen** [comment]
Ah, that makes more sense.  I did break the generate button about a month ago.  The issue should be fixed in the latest development branch commit from about three weeks ago.  Do you have the latest version?

**Comment by yoderjen** [comment]
I found the problem and checked in the fix.  Get the newest version of the development branch (should have just been updated) and it will fix your problem.  Thanks for the report!

**Comment by mskmoorthy** [comment]
Thanks - works Like a charm!
