### ISSUE TITLE
Collaboration with OpenJSCAD.org

### ISSUE THREAD

**Issue by z3dev** [EinsteinsWorkshop/BlocksCAD#37]
It seams that this project is making some changes to common libraries which both BlocksCAD and OpenJSCAD.org are using. How about some collaboration on these libraries, which can benefit both projects.

**Comment by yoderjen** [comment]
Sounds good.  What did you have in mind?

**Comment by z3dev** [comment]
Thanks! I started watching this repository for conversations, and pull requests. If you haven't already then you might want to start watching our repository at https://github.com/Spiritdude/OpenJSCAD.org

There's a major reorganization of the source happening now. This will allow easier integration into NODE based projects. And we hope that this will allow others to make further innovations to OpenJSCAD.org as well.

**Comment by z3dev** [comment]
Where to start...

We contribute to these libraries frequently, and would like to make sure that changes are integrated back to the original.
- CSG.js
- formats.js

We also use the openscad-openjscad-translator.js library but there is no maintanance planned on the original. It would be great to contribute on this library if possible. Ideas?

**Comment by yoderjen** [comment]
Are you guys working on OpenJScad.org or are you working on a different product?

the openscad parser (openscad-openjscad-translator) is out of date and buggy as well.  I've been trying to debug it but haven't had any luck extending it for the new openscad language features.

**Comment by z3dev** [comment]
OpenJSCAD.org is the URL

We are also setting up an organization to manage all the connected libraries. If interested then please let me know. You are welcome to use any of these libraries and contribute as well.

https://github.com/jscad

**Comment by z3dev** [comment]
@yoderjen The new organization is live. The authors of CSG.js and openscad-openjscad-translator have agreed that these would both be better under a single organization.

Please consider joining. We would love to have any contributions from this project as well.

**Comment by z3dev** [comment]
Wouldn't your changes be better as part of the JSCAD open library?
If you don't mind then I will start merging changes from the translator source into the same at JSCAD open library; https://github.com/jscad/openscad-openjscad-translator

**Comment by z3dev** [comment]
So.... we have released 1.0.0 which should make integration easier.... we hope.

Let us know if you have any isssues.

**Comment by WolfgangFahl** [comment]
see my comment at https://openjscad.nodebb.com/topic/8/cooperation-with-blockscad
