### ISSUE TITLE
how to generate language files? I want to translate the soft into Chinese

### ISSUE THREAD

**Issue by shytears** [EinsteinsWorkshop/BlocksCAD#39]
I can use "js_to_json.py“to generate zh.json, and then modify it. At last, use "create_massges.py" to generate zh.js.
But, after that, there is no changes on the webside.
please tell me the right processes to generate language files.

**Comment by yoderjen** [comment]
You need to submit the zh.json file as a pull request so I can add it to our code base, then I'll have to release it to the blockscad3d.com website.

**Comment by shytears** [comment]
ok. thanks for you reply so rapidly! This is my first project on github.I will do this in these day.

ps: Anther question is that , I use 2D/3D text block and it didn't works. When i press render button, it turns into working and gray contiousely, as shown blow. Then I have to reflash the web side.
the running evironment is runing the website localy , with the index.html in the directory, didn't pulic it with the web service.
![image](https://cloud.githubusercontent.com/assets/23303695/23089200/63c8d91a-f5c0-11e6-9d09-5bb9155c4031.png)

**Comment by yoderjen** [comment]
The fonts aren't being loaded.  The font library we use (opentype.js) needs a web server to load the fonts.  So when you are running code locally, you'll need to run a web server, which is easy.  From the root directory (with index.html in it), you can run an http server - I recommend either using Node.js's server or Python's.

The node server command is http-server -p 8888  (use whatever number you want the port to be).  You'd then go to

localhost:8888  

in the browser to see the page.

read the README for the instructions on how to run the python simplehttpserver.

**Comment by shytears** [comment]
I've sent a pull request for Chinese language file.
Because it's the first time I use pull request, I have sent a zipped zh.json file. I hope that I have done a right thing.
