### ISSUE TITLE
Model is not on a closed surface 

### ISSUE THREAD

**Issue by osupk8** [EinsteinsWorkshop/BlocksCAD#45]
Hi,

I want to point a bug I found using a model I created today : https://www.blockscad3d.com/community/projects/43698

When I tried to export this model in STL format to my 3D printer I got the message : "Model is not on a closed surface"
And when I try to print this model it fails. I also have trouble when i try to import this STL model in tinkercad,etc it bugs.
Perhaps the problem  is in STL générator ?

Indedd, I take the code of this model and I copy/paste it  in opensCAD software and when I export the model in STL it works fine on my printer.

Best regards

Christophe

**Comment by yoderjen** [comment]
What slicer/printer are you using?

**Comment by osupk8** [comment]
Dremel3D slicer

----- Mail original -----
De: "yoderjen" <notifications@github.com>
À: "EinsteinsWorkshop/BlocksCAD" <BlocksCAD@noreply.github.com>
Cc: "osupk8" <osupk8@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 9 Juillet 2017 18:39:05
Objet: Re: [EinsteinsWorkshop/BlocksCAD] Model is not on a closed surface (#45)



What slicer/printer are you using?

**Comment by yoderjen** [comment]
Added some mesh repair before STL download.  It doesn't fix all models, but is a start.
