### ISSUE TITLE
Match OpenSCAD features

### ISSUE THREAD

**Issue by mattminuti** [EinsteinsWorkshop/BlocksCAD#5]
There's a number of features that we're missing, and if we want to be fully OpenSCAD-compatible, we need to add them.

Working from the [OpenSCAD cheatsheet](http://www.openscad.org/cheatsheet/index.html), just looking at shape generation:
- [ ] Projection
- [ ] Minkowski Sum
- [ ] Children
- [ ] Resize
- [ ] Offset
- [ ] Polygon
- [ ] Polyhedron
- [ ] Surface

**Comment by yoderjen** [comment]
The goal of BlocksCAD isn't to be fully openSCAD compatible, but to present a subset of openSCAD that contains most of its usefulness to beginning and intermediate programmers while reducing the complexity.  If there are certain features of OpenSCAD that we don't implement that you feel would be especially helpful, please let us know and give a description of why that feature will be useful.
